name: Deploying Springboot(War) to Tomcat on Azure Windows Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-springboot-app:
    name: Build Springboot Application
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version

      - name: Download the code
        uses: actions/checkout@v3

      - name: Fix the Permissons of mvnw command
        run: chmod +x mvnw

      - name: Build the code
        run: ./mvnw package

      - name: Verify the Build is Created or Not
        run: ls -l target/*.war

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 20.55.34.125
          username: dana
          password: Danayusuf123
          port: 22
          source: 'target/apisrvice-0.0.1-SNAPSHOT.war'
          target: 'C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps'

        # - name: Deploy the Build to Tomcat

